<ul class="menu">
	<li><a href="<?php echo $this->url(array('action'=>'overview'),'doc',true); ?>" class="overview"><?php echo $this->translate('overview'); ?></a></li>
	<li><a href="<?php echo $this->url(array('action'=>'packages'),'doc',true); ?>" class="packages"><?php echo $this->translate('packages'); ?></a></li>
	<li><a href="<?php echo $this->url(array('action'=>'all'),'doc',true); ?>" class="index"><?php echo $this->translate('index'); ?></a></li>
</ul>
