<h2><?php echo $this->translate($this->title); ?></h2>

<p><?php echo $this->translate('general_error_message'); ?></p>
<p><?php echo $this->translate('our_team_is_working_to_resolve_this_asap'); ?></p>
<p><?php echo $this->translate('sorry'); ?></p>
 
<?php if ($this->exception) { ?>      
<p>
	<strong><?php echo $this->exception->getMessage(); ?></strong>
</p>
<pre>
	<?php //var_dump($this->exception->getTrace()); ?>
</pre>
<?php } ?>