<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $this->escape($this->pageTitle.' - ' . $this->configuration()->version); ?></title>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="icon" type="image/png" href="/favicon.png" />
    <link type="text/css" rel="StyleSheet" media="screen" href="/share/css/screen.css"/>
	<script type="text/javascript" src="/share/js/mootools-trunk-1547.js" ></script>

	<?php echo $this->headScript(); ?>
	<?php echo $this->inlineScript(); ?>

</head>
<body>
	<?php echo $this->layout()->content;?>
</body>
</html>
